#!/bin/bash

apt-get install python-dbus

mkdir /usr/share/cautotest
cp ./*.py /usr/share/cautotest/

ln -s /usr/share/cautotest/main.py /usr/local/bin/cautotest

cp ./cautotest.comp /etc/bash_completion.d/cautotest &&
echo "Please, restart terminal for autocomplete"
